use crate::models::ShellAlias;
use std::collections::HashSet;

#[derive(Debug, Clone, PartialEq)]
pub enum Shell {
    PowerShell,
    Bash,
    Zsh,
    Fish,
}

impl Shell {
    pub fn from_str(s: &str) -> Option<Self> {
        match s.to_lowercase().as_str() {
            "powershell" | "pwsh" | "ps" => Some(Shell::PowerShell),
            "bash" => Some(Shell::Bash),
            "zsh" => Some(Shell::Zsh),
            "fish" => Some(Shell::Fish),
            _ => None,
        }
    }

    fn key(&self) -> &'static str {
        match self {
            Shell::PowerShell => "powershell",
            Shell::Bash => "bash",
            Shell::Zsh => "zsh",
            Shell::Fish => "fish",
        }
    }
}

const SHELL_BUILTINS: &[&str] = &[
    "cd", "exit", "source", "eval", "exec", "export", "alias", "unalias",
    "set", "unset", "return", "shift", "test", "true", "false", "echo",
    "printf", "read", "type", "which", "command",
];

/// Validate an alias name. Returns Ok(()) if valid, Err with message otherwise.
pub fn validate_alias_name(name: &str) -> Result<(), String> {
    if name.is_empty() {
        return Err("Alias name cannot be empty".to_string());
    }
    if name.contains(char::is_whitespace) {
        return Err("Alias name cannot contain spaces".to_string());
    }
    if !name.chars().all(|c| c.is_alphanumeric() || c == '_' || c == '-') {
        return Err("Alias name can only contain alphanumeric characters, hyphens, and underscores".to_string());
    }
    Ok(())
}

/// Validate alias_type value.
pub fn validate_alias_type(alias_type: &str) -> Result<(), String> {
    match alias_type {
        "function" | "script" | "init" => Ok(()),
        _ => Err(format!(
            "Invalid alias type '{}'. Must be one of: function, script, init",
            alias_type
        )),
    }
}

/// Check if the alias name shadows a common shell builtin.
pub fn is_shell_builtin(name: &str) -> bool {
    SHELL_BUILTINS.iter().any(|b| b.eq_ignore_ascii_case(name))
}

/// Generate shell init script for the given aliases.
/// Aliases with `execution_order` set appear first (sorted ascending),
/// followed by those without (sorted by `order`). With `shell_integration`
/// the OSC 7 / 133 block from [`shell_integration_snippet`] is appended
/// last, so it wraps whatever prompt the aliases (starship, oh-my-posh…)
/// installed.
pub fn generate_init_script(shell: &Shell, aliases: &[ShellAlias], shell_integration: bool) -> String {
    generate_init_script_ext(
        shell,
        aliases,
        InitOptions {
            shell_integration,
            disable_shell_predictions: false,
        },
    )
}

/// Knobs of the generated init script (from `settings.terminal`).
#[derive(Debug, Clone, Copy, Default)]
pub struct InitOptions {
    /// Emit the OSC 7 / 133 block.
    pub shell_integration: bool,
    /// CortX draws its own history ghost text, so the shell's inline
    /// prediction (PSReadLine) is switched off inside CortX terminals to
    /// avoid two suggestions at once.
    pub disable_shell_predictions: bool,
}

pub fn generate_init_script_ext(shell: &Shell, aliases: &[ShellAlias], opts: InitOptions) -> String {
    let shell_integration = opts.shell_integration;
    let shell_key = shell.key();

    // Sort: execution_order set first (ascending), then the rest by order
    let mut sorted: Vec<&ShellAlias> = aliases.iter().collect();
    sorted.sort_by(|a, b| {
        match (a.execution_order, b.execution_order) {
            (Some(ao), Some(bo)) => ao.cmp(&bo),
            (Some(_), None) => std::cmp::Ordering::Less,
            (None, Some(_)) => std::cmp::Ordering::Greater,
            (None, None) => a.order.cmp(&b.order),
        }
    });

    let mut output = String::new();
    output.push_str("# CortX shell aliases — generated by `cortx init`\n");
    output.push_str(&format!(
        "# Do not edit manually; re-run `cortx init {}` to update.\n\n",
        shell_key
    ));

    // Track tool_ids whose setup has already been emitted (deduplicate)
    let mut setup_emitted: HashSet<String> = HashSet::new();

    for alias in &sorted {
        // 1. Description comment
        if let Some(ref desc) = alias.description {
            output.push_str(&format!("# {}\n", desc));
        }

        // 2. Setup code (deduplicated by tool_id)
        if let Some(ref setup_map) = alias.setup {
            if let Some(setup_code) = setup_map.get(shell_key) {
                if !setup_code.trim().is_empty() {
                    let should_emit = match &alias.tool_id {
                        Some(tid) => setup_emitted.insert(tid.clone()),
                        None => true, // no tool_id => always emit
                    };
                    if should_emit {
                        output.push_str(setup_code);
                        if !setup_code.ends_with('\n') {
                            output.push('\n');
                        }
                    }
                }
            }
        }

        // 3. Alias body
        let alias_type = alias.alias_type.as_str();
        match alias_type {
            "script" => {
                if let Some(ref script_map) = alias.script {
                    if let Some(script_code) = script_map.get(shell_key) {
                        if !script_code.trim().is_empty() {
                            output.push_str(script_code);
                            if !script_code.ends_with('\n') {
                                output.push('\n');
                            }
                        }
                    }
                }
            }
            "init" => {
                if let Some(ref script_map) = alias.script {
                    if let Some(init_cmd) = script_map.get(shell_key) {
                        if !init_cmd.trim().is_empty() {
                            match shell {
                                Shell::PowerShell => {
                                    output.push_str(&format!(
                                        "Invoke-Expression (& {{ ({} | Out-String) }})\n",
                                        init_cmd.trim()
                                    ));
                                }
                                Shell::Bash | Shell::Zsh => {
                                    output.push_str(&format!(
                                        "eval \"$({})\"\n",
                                        init_cmd.trim()
                                    ));
                                }
                                Shell::Fish => {
                                    output.push_str(&format!(
                                        "{} | source\n",
                                        init_cmd.trim()
                                    ));
                                }
                            }
                        }
                    }
                }
            }
            _ => {
                // "function" (default) — original wrapping logic
                match shell {
                    Shell::PowerShell => {
                        // A statement that starts with a quote parses in
                        // *expression* mode, where the splatting operator
                        // `@args` is illegal — and since `cortx init` output is
                        // consumed by a single Invoke-Expression, one such alias
                        // is a parse error that takes down the whole block, not
                        // just itself. The call operator `&` forces command mode.
                        //
                        // Quoting is required in the stored command as soon as
                        // the path holds a space (the .cmd and .sh shims have no
                        // call operator to fall back on), so the generator is
                        // where the PowerShell-specific syntax has to be added.
                        let cmd = alias.command.trim();
                        let call_op = if cmd.starts_with('"') || cmd.starts_with('\'') {
                            "& "
                        } else {
                            ""
                        };
                        output.push_str(&format!(
                            "function {} {{ {}{} @args }}\n",
                            alias.name, call_op, cmd
                        ));
                    }
                    Shell::Bash | Shell::Zsh => {
                        let escaped_cmd = alias.command.replace('\'', "'\\''");
                        output.push_str(&format!(
                            "{}() {{ {} \"$@\"; }}\n",
                            alias.name, escaped_cmd
                        ));
                    }
                    Shell::Fish => {
                        output.push_str(&format!(
                            "function {}\n    {} $argv\nend\n",
                            alias.name, alias.command
                        ));
                    }
                }
            }
        }
    }

    if shell_integration {
        output.push('\n');
        output.push_str(&shell_integration_block(shell));
    }

    if opts.disable_shell_predictions && *shell == Shell::PowerShell {
        output.push_str(DISABLE_PSREADLINE_PREDICTION);
    }

    output
}

/// Turns PSReadLine's own inline prediction off inside a CortX terminal, so
/// it does not double up with our ghost text.
///
/// One line on purpose: it has to survive a line-by-line `Invoke-Expression`.
/// It checks that the parameter exists before using it — `-PredictionSource`
/// only arrived in PSReadLine 2.1, and Windows PowerShell 5.1 still ships 2.0,
/// where the call throws a binding error in the user's face at every prompt.
const DISABLE_PSREADLINE_PREDICTION: &str = "if ($env:CORTX_TERMINAL_ID -and (Get-Module -Name PSReadLine) -and (Get-Command Set-PSReadLineOption -ErrorAction SilentlyContinue | Where-Object { $_.Parameters.ContainsKey('PredictionSource') })) { Set-PSReadLineOption -PredictionSource None }\n";

/// Which shell a program name is, for the app-side injection (`pwsh.exe`,
/// `/bin/zsh`, `fish`…). `None` for anything we have no snippet for.
pub fn shell_for_program(program: &str) -> Option<Shell> {
    let base = std::path::Path::new(program)
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or(program)
        .to_ascii_lowercase();
    match base.as_str() {
        "pwsh" | "powershell" => Some(Shell::PowerShell),
        "bash" => Some(Shell::Bash),
        "zsh" => Some(Shell::Zsh),
        "fish" => Some(Shell::Fish),
        _ => None,
    }
}

/// The integration as *startup code* the app hands to a shell it spawns, so
/// it works even when the profile does not call `cortx init` (or calls an
/// older CLI). PowerShell gets one `Invoke-Expression` statement per line
/// (joined by `;` by the caller); other shells get the block verbatim.
pub fn shell_integration_startup(shell: &Shell, opts: InitOptions) -> String {
    let mut out = String::new();
    if opts.shell_integration {
        out.push_str(&shell_integration_block(shell));
    }
    if opts.disable_shell_predictions && *shell == Shell::PowerShell {
        out.push_str(DISABLE_PSREADLINE_PREDICTION);
    }
    out
}

/// The integration snippet in the form that goes into the init script.
/// PowerShell gets a single `Invoke-Expression` line carrying the block as
/// base64, so it survives both `| Out-String | Invoke-Expression` and a
/// line-by-line `| Invoke-Expression`. Other shells eval the whole output
/// at once and get the block verbatim.
pub fn shell_integration_block(shell: &Shell) -> String {
    let snippet = shell_integration_snippet(shell);
    match shell {
        Shell::PowerShell => {
            use base64::Engine;
            let b64 = base64::engine::general_purpose::STANDARD.encode(snippet.as_bytes());
            format!(
                "# CortX shell integration (OSC 7 / OSC 133); decoded and evaluated as one block\n\
                 Invoke-Expression ([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('{}')))\n",
                b64
            )
        }
        _ => snippet.to_string(),
    }
}

// ---------------------------------------------------------------------------
// Sub-shells (ticket #16 — "warpify")
// ---------------------------------------------------------------------------

/// Single quoting for POSIX shells (`'` closes, escapes, reopens).
fn sq(value: &str) -> String {
    format!("'{}'", value.replace('\'', r"'\''"))
}

/// The integration as **one line typed into an already-running shell**.
///
/// The startup injection in `process_manager::inject_shell_integration` only
/// reaches the shell CortX spawns itself. A shell started *inside* it — `bash`
/// from PowerShell, `docker exec -it … bash`, `ssh host`, `wsl` — has to be
/// handed the block after the fact, which is what Warp calls "warpifying" a
/// sub-shell. Warp does it by typing a bootstrap into the PTY; so do we.
///
/// The line is self-contained on purpose: it carries the block base64-encoded
/// and sets `CORTX_TERMINAL_ID` itself, so it also works where the variable
/// was not inherited (ssh, containers, WSL) and where `cortx` is not
/// installed. It starts with a space so shells configured to ignore
/// space-prefixed lines keep it out of the history.
///
/// **Never send this to something that is not a shell.** A CortX terminal
/// cannot tell an interactive `python` from a `bash`, so this is only ever
/// emitted on an explicit user action (see `components/terminal/subshell.ts`).
pub fn subshell_injection(shell: &Shell, terminal_id: &str, opts: InitOptions) -> String {
    use base64::Engine;
    let b64 = base64::engine::general_purpose::STANDARD.encode(shell_integration_snippet(shell).as_bytes());
    match shell {
        Shell::PowerShell => {
            // PowerShell needs no base64 helper on the far side: it decodes
            // the block itself. (Warp declines PowerShell sub-shells; we can
            // do them, because our block is already a single statement.)
            let mut line = format!(
                " $env:CORTX_TERMINAL_ID = '{}'; Invoke-Expression ([Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('{}')))",
                terminal_id.replace('\'', "''"),
                b64
            );
            if opts.disable_shell_predictions {
                line.push_str("; ");
                line.push_str(DISABLE_PSREADLINE_PREDICTION.trim_end());
            }
            line
        }
        Shell::Fish => format!(
            " set -gx CORTX_TERMINAL_ID {}; printf %s {} | base64 -d 2>/dev/null | source",
            sq(terminal_id),
            sq(&b64)
        ),
        // bash and zsh: `base64 -d` on GNU coreutils, `-D` on the older BSD
        // tool that still ships on macOS.
        _ => format!(
            " CORTX_TERMINAL_ID={0}; export CORTX_TERMINAL_ID; eval \"$(printf %s {1} | {{ base64 -d 2>/dev/null || base64 -D; }})\"",
            sq(terminal_id),
            sq(&b64)
        ),
    }
}

/// Shell-integration block appended by `cortx init` when
/// `settings.terminal.shell_integration` is on. Every shell guards on
/// `CORTX_TERMINAL_ID` (set by CortX's PTYs) so external terminals never see
/// the sequences. Protocol: OSC 7 for the cwd, OSC 133 A/B/C/D for prompt and
/// command boundaries, with `C;cmd=<base64 utf-8>` carrying the command line.
/// Parsed by `terminal::osc`.
pub fn shell_integration_snippet(shell: &Shell) -> &'static str {
    match shell {
        Shell::PowerShell => POWERSHELL_INTEGRATION,
        Shell::Bash => BASH_INTEGRATION,
        Shell::Zsh => ZSH_INTEGRATION,
        Shell::Fish => FISH_INTEGRATION,
    }
}

const POWERSHELL_INTEGRATION: &str = r##"
# --- CortX shell integration (OSC 7 / OSC 133) — active only inside a CortX terminal ---
if ($env:CORTX_TERMINAL_ID) {
    $global:__cortx_ran = $false
    function global:__cortx_urlencode([string]$p) {
        return $p.Replace('%', '%25').Replace(' ', '%20').Replace('#', '%23').Replace('?', '%3F')
    }
    function global:__cortx_wrap_prompt {
        $inner = $function:prompt
        if ($inner -and $inner.ToString().Contains('__cortx_marks')) { return }
        $global:__cortx_inner_prompt = $inner
        function global:prompt {
            $lastSuccess = $?
            $gle = $global:LASTEXITCODE
            # __cortx_marks
            $inner = $global:__cortx_inner_prompt
            $loc = $ExecutionContext.SessionState.Path.CurrentLocation
            $text = if ($inner) { & $inner } else { "PS $loc> " }
            $e = [char]27; $b = [char]7
            $out = ''
            if ($global:__cortx_ran) {
                $code = if ($lastSuccess) { 0 } elseif ($gle -is [int] -and $gle -ne 0) { $gle } else { 1 }
                $out += "$e]133;D;$code$b"
                $global:__cortx_ran = $false
            }
            if ($loc.Provider.Name -eq 'FileSystem') {
                $p = $loc.ProviderPath -replace '\\', '/'
                if (-not $p.StartsWith('/')) { $p = "/$p" }
                $out += "$e]7;file://localhost$(__cortx_urlencode $p)$b"
            }
            $out += "$e]133;A$b"
            $out += ($text -join '')
            $out += "$e]133;B$b"
            $global:LASTEXITCODE = $gle
            return $out
        }
    }
    __cortx_wrap_prompt
    if (Get-Module -Name PSReadLine) {
        Set-PSReadLineKeyHandler -Key Enter -BriefDescription CortXAcceptLine -Description 'Accept the line and mark the command start for CortX' -ScriptBlock {
            $line = $null; $cursor = $null
            [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cursor)
            if ($line -and $line.Trim()) {
                $b64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($line))
                [Console]::Write("$([char]27)]133;C;cmd=$b64$([char]7)")
                $global:__cortx_ran = $true
            }
            __cortx_wrap_prompt
            [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine()
        }
    }
}
"##;

const BASH_INTEGRATION: &str = r##"
# --- CortX shell integration (OSC 7 / OSC 133) — active only inside a CortX terminal ---
if [ -n "$CORTX_TERMINAL_ID" ] && [ -n "$BASH_VERSION" ]; then
  __cortx_osc() { printf '\033]%s\007' "$1"; }
  __cortx_urlencode() { local s="$1"; s="${s//%/%25}"; s="${s// /%20}"; s="${s//#/%23}"; s="${s//\?/%3F}"; printf '%s' "$s"; }
  __cortx_preexec() {
    [ "$__cortx_mode" = on ] || return 0
    __cortx_mode=off
    [ -n "$COMP_LINE" ] && return 0
    local cmd
    cmd=$(HISTTIMEFORMAT= builtin history 1 2>/dev/null | sed 's/^ *[0-9]* *//')
    [ -z "$cmd" ] && cmd="$BASH_COMMAND"
    __cortx_osc "133;C;cmd=$(printf '%s' "$cmd" | base64 2>/dev/null | tr -d '\n')"
    __cortx_ran=1
  }
  __cortx_precmd() {
    local ec=$?
    if [ -n "$__cortx_ran" ]; then __cortx_osc "133;D;$ec"; __cortx_ran=; fi
    __cortx_osc "7;file://${HOSTNAME:-localhost}$(__cortx_urlencode "$PWD")"
    __cortx_osc "133;A"
  }
  __cortx_precmd_last() {
    case "$PS1" in *'133;B'*) ;; *) PS1="${PS1}"'\[\e]133;B\a\]' ;; esac
    __cortx_mode=on
  }
  PROMPT_COMMAND="__cortx_precmd${PROMPT_COMMAND:+;$PROMPT_COMMAND};__cortx_precmd_last"
  trap '__cortx_preexec' DEBUG
fi
"##;

const ZSH_INTEGRATION: &str = r##"
# --- CortX shell integration (OSC 7 / OSC 133) — active only inside a CortX terminal ---
if [[ -n "$CORTX_TERMINAL_ID" && -n "$ZSH_VERSION" ]]; then
  autoload -Uz add-zsh-hook
  __cortx_osc() { printf '\033]%s\007' "$1"; }
  __cortx_urlencode() { local s="$1"; s="${s//\%/%25}"; s="${s// /%20}"; s="${s//\#/%23}"; s="${s//\?/%3F}"; printf '%s' "$s"; }
  __cortx_preexec() {
    __cortx_osc "133;C;cmd=$(printf '%s' "$1" | base64 2>/dev/null | tr -d '\n')"
    __cortx_ran=1
  }
  __cortx_precmd() {
    local ec=$?
    if [[ -n "$__cortx_ran" ]]; then __cortx_osc "133;D;$ec"; __cortx_ran=; fi
    __cortx_osc "7;file://${HOST:-localhost}$(__cortx_urlencode "$PWD")"
    __cortx_osc "133;A"
    [[ "$PS1" == *'133;B'* ]] || PS1="${PS1}%{$(printf '\033]133;B\007')%}"
  }
  add-zsh-hook preexec __cortx_preexec
  add-zsh-hook precmd __cortx_precmd
fi
"##;

const FISH_INTEGRATION: &str = r##"
# --- CortX shell integration (OSC 7 / OSC 133) — active only inside a CortX terminal ---
if set -q CORTX_TERMINAL_ID
    function __cortx_osc
        printf '\033]%s\007' $argv[1]
    end
    function __cortx_urlencode
        string replace -a '%' '%25' -- $argv[1] | string replace -a ' ' '%20' | string replace -a '#' '%23' | string replace -a '?' '%3F'
    end
    function __cortx_preexec --on-event fish_preexec
        set -g __cortx_ran 1
        __cortx_osc "133;C;cmd="(printf '%s' $argv[1] | base64 2>/dev/null | string join '')
    end
    function __cortx_postexec --on-event fish_postexec
        set -l ec $status
        if set -q __cortx_ran
            __cortx_osc "133;D;$ec"
            set -e __cortx_ran
        end
    end
    function __cortx_prompt --on-event fish_prompt
        __cortx_osc "7;file://"(hostname)(__cortx_urlencode $PWD)
        __cortx_osc "133;A"
        __cortx_osc "133;B"
    end
end
"##;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn integration_block_is_appended_last_and_guarded() {
        for shell in [Shell::PowerShell, Shell::Bash, Shell::Zsh, Shell::Fish] {
            let a = func_alias("hi", "echo hi");
            let with = generate_init_script(&shell, std::slice::from_ref(&a), true);
            let without = generate_init_script(&shell, std::slice::from_ref(&a), false);
            assert!(with.starts_with(&without), "{:?}", shell);
            assert!(!without.contains("133;A"), "{:?}", shell);
            let snippet = shell_integration_snippet(&shell);
            assert!(with.contains(&shell_integration_block(&shell)), "{:?}", shell);
            assert!(snippet.contains("CORTX_TERMINAL_ID"), "{:?}", shell);
            assert!(snippet.contains("133;A"), "{:?}", shell);
            assert!(snippet.contains("133;C;cmd="), "{:?}", shell);
            assert!(snippet.contains("133;D"), "{:?}", shell);
            assert!(snippet.contains("7;file://"), "{:?}", shell);
        }
    }

    #[test]
    fn powershell_block_is_one_base64_line_that_decodes_to_the_snippet() {
        use base64::Engine;
        let block = shell_integration_block(&Shell::PowerShell);
        let code_lines: Vec<&str> = block.lines().filter(|l| !l.starts_with('#')).collect();
        assert_eq!(code_lines.len(), 1, "{}", block);
        let line = code_lines[0];
        let start = line.find("FromBase64String('").unwrap() + "FromBase64String('".len();
        let end = line[start..].find('\'').unwrap() + start;
        let decoded = base64::engine::general_purpose::STANDARD.decode(&line[start..end]).unwrap();
        assert_eq!(String::from_utf8(decoded).unwrap(), shell_integration_snippet(&Shell::PowerShell));
    }

    fn func_alias(name: &str, command: &str) -> ShellAlias {
        ShellAlias::new(name.to_string(), command.to_string())
    }

    #[test]
    fn subshell_injection_is_a_single_space_prefixed_line_per_shell() {
        for shell in [Shell::PowerShell, Shell::Bash, Shell::Zsh, Shell::Fish] {
            let line = subshell_injection(&shell, "shell:abc", InitOptions::default());
            assert!(line.starts_with(' '), "{shell:?}: {line}");
            assert!(!line.contains('\n'), "{shell:?}: {line}");
            assert!(line.contains("shell:abc"), "{shell:?}: {line}");
            assert!(line.contains("CORTX_TERMINAL_ID"), "{shell:?}: {line}");
        }
    }

    #[test]
    fn subshell_injection_carries_the_whole_block() {
        use base64::Engine;
        for shell in [Shell::PowerShell, Shell::Bash, Shell::Zsh, Shell::Fish] {
            let line = subshell_injection(&shell, "shell:abc", InitOptions::default());
            let b64 = base64::engine::general_purpose::STANDARD.encode(shell_integration_snippet(&shell).as_bytes());
            assert!(line.contains(&b64), "{shell:?} does not carry its own snippet");
        }
    }

    #[test]
    fn subshell_injection_quotes_a_hostile_terminal_id() {
        let line = subshell_injection(&Shell::Bash, "shell:'; rm -rf /; #", InitOptions::default());
        // The quote is closed, escaped and reopened, so the rest stays a
        // literal value instead of becoming a second command.
        assert!(line.contains(r#"CORTX_TERMINAL_ID='shell:'\''; rm -rf /; #'"#), "{line}");
        let pwsh = subshell_injection(&Shell::PowerShell, "shell:'; rm x", InitOptions::default());
        assert!(pwsh.contains("$env:CORTX_TERMINAL_ID = 'shell:''; rm x'"), "{pwsh}");
    }

    #[test]
    fn powershell_subshell_injection_can_add_the_psreadline_guard() {
        let opts = InitOptions { shell_integration: true, disable_shell_predictions: true };
        let line = subshell_injection(&Shell::PowerShell, "shell:abc", opts);
        assert!(line.contains("Set-PSReadLineOption"), "{line}");
        assert!(!line.contains('\n'), "{line}");
    }

    #[test]
    fn powershell_quoted_command_gets_the_call_operator() {
        let a = func_alias("payledger", r#""C:\Users\Alexis Munch\payledger.exe""#);
        let out = generate_init_script(&Shell::PowerShell, std::slice::from_ref(&a), false);
        assert!(
            out.contains(r#"function payledger { & "C:\Users\Alexis Munch\payledger.exe" @args }"#),
            "got: {out}"
        );
    }

    #[test]
    fn powershell_bare_command_is_left_alone() {
        // Starts with a command word: already command mode, `&` would be noise.
        let a = func_alias("onepack", r#"bun run "C:\a b\x.ts""#);
        let out = generate_init_script(&Shell::PowerShell, std::slice::from_ref(&a), false);
        assert!(
            out.contains(r#"function onepack { bun run "C:\a b\x.ts" @args }"#),
            "got: {out}"
        );
        assert!(!out.contains("{ &"), "got: {out}");
    }

    #[test]
    fn powershell_existing_call_operator_is_not_doubled() {
        let a = func_alias("zorg", r#"& "C:\a b\zorg.exe""#);
        let out = generate_init_script(&Shell::PowerShell, std::slice::from_ref(&a), false);
        assert!(out.contains(r#"{ & "C:\a b\zorg.exe" @args }"#), "got: {out}");
        assert!(!out.contains("& &"), "got: {out}");
    }

    #[test]
    fn posix_shells_need_no_call_operator() {
        // In sh and fish a quoted string is a perfectly good command word.
        let a = func_alias("payledger", r#""/opt/a b/payledger""#);
        let bash = generate_init_script(&Shell::Bash, std::slice::from_ref(&a), false);
        assert!(bash.contains(r#"payledger() { "/opt/a b/payledger" "$@"; }"#), "got: {bash}");
        let fish = generate_init_script(&Shell::Fish, std::slice::from_ref(&a), false);
        assert!(fish.contains(r#""/opt/a b/payledger" $argv"#), "got: {fish}");
    }
}
