use crate::models::ShellAlias;
use std::collections::HashSet;

#[derive(Debug, Clone, PartialEq)]
pub enum Shell {
    PowerShell,
    Bash,
    Zsh,
    Fish,
}

impl Shell {
    pub fn from_str(s: &str) -> Option<Self> {
        match s.to_lowercase().as_str() {
            "powershell" | "pwsh" | "ps" => Some(Shell::PowerShell),
            "bash" => Some(Shell::Bash),
            "zsh" => Some(Shell::Zsh),
            "fish" => Some(Shell::Fish),
            _ => None,
        }
    }

    fn key(&self) -> &'static str {
        match self {
            Shell::PowerShell => "powershell",
            Shell::Bash => "bash",
            Shell::Zsh => "zsh",
            Shell::Fish => "fish",
        }
    }
}

const SHELL_BUILTINS: &[&str] = &[
    "cd", "exit", "source", "eval", "exec", "export", "alias", "unalias",
    "set", "unset", "return", "shift", "test", "true", "false", "echo",
    "printf", "read", "type", "which", "command",
];

/// Validate an alias name. Returns Ok(()) if valid, Err with message otherwise.
pub fn validate_alias_name(name: &str) -> Result<(), String> {
    if name.is_empty() {
        return Err("Alias name cannot be empty".to_string());
    }
    if name.contains(char::is_whitespace) {
        return Err("Alias name cannot contain spaces".to_string());
    }
    if !name.chars().all(|c| c.is_alphanumeric() || c == '_' || c == '-') {
        return Err("Alias name can only contain alphanumeric characters, hyphens, and underscores".to_string());
    }
    Ok(())
}

/// Validate alias_type value.
pub fn validate_alias_type(alias_type: &str) -> Result<(), String> {
    match alias_type {
        "function" | "script" | "init" => Ok(()),
        _ => Err(format!(
            "Invalid alias type '{}'. Must be one of: function, script, init",
            alias_type
        )),
    }
}

/// Check if the alias name shadows a common shell builtin.
pub fn is_shell_builtin(name: &str) -> bool {
    SHELL_BUILTINS.iter().any(|b| b.eq_ignore_ascii_case(name))
}

/// Generate shell init script for the given aliases.
/// Aliases with `execution_order` set appear first (sorted ascending),
/// followed by those without (sorted by `order`).
pub fn generate_init_script(shell: &Shell, aliases: &[ShellAlias]) -> String {
    let shell_key = shell.key();

    // Sort: execution_order set first (ascending), then the rest by order
    let mut sorted: Vec<&ShellAlias> = aliases.iter().collect();
    sorted.sort_by(|a, b| {
        match (a.execution_order, b.execution_order) {
            (Some(ao), Some(bo)) => ao.cmp(&bo),
            (Some(_), None) => std::cmp::Ordering::Less,
            (None, Some(_)) => std::cmp::Ordering::Greater,
            (None, None) => a.order.cmp(&b.order),
        }
    });

    let mut output = String::new();
    output.push_str("# CortX shell aliases — generated by `cortx init`\n");
    output.push_str(&format!(
        "# Do not edit manually; re-run `cortx init {}` to update.\n\n",
        shell_key
    ));

    // Track tool_ids whose setup has already been emitted (deduplicate)
    let mut setup_emitted: HashSet<String> = HashSet::new();

    for alias in &sorted {
        // 1. Description comment
        if let Some(ref desc) = alias.description {
            output.push_str(&format!("# {}\n", desc));
        }

        // 2. Setup code (deduplicated by tool_id)
        if let Some(ref setup_map) = alias.setup {
            if let Some(setup_code) = setup_map.get(shell_key) {
                if !setup_code.trim().is_empty() {
                    let should_emit = match &alias.tool_id {
                        Some(tid) => setup_emitted.insert(tid.clone()),
                        None => true, // no tool_id => always emit
                    };
                    if should_emit {
                        output.push_str(setup_code);
                        if !setup_code.ends_with('\n') {
                            output.push('\n');
                        }
                    }
                }
            }
        }

        // 3. Alias body
        let alias_type = alias.alias_type.as_str();
        match alias_type {
            "script" => {
                if let Some(ref script_map) = alias.script {
                    if let Some(script_code) = script_map.get(shell_key) {
                        if !script_code.trim().is_empty() {
                            output.push_str(script_code);
                            if !script_code.ends_with('\n') {
                                output.push('\n');
                            }
                        }
                    }
                }
            }
            "init" => {
                if let Some(ref script_map) = alias.script {
                    if let Some(init_cmd) = script_map.get(shell_key) {
                        if !init_cmd.trim().is_empty() {
                            match shell {
                                Shell::PowerShell => {
                                    output.push_str(&format!(
                                        "Invoke-Expression (& {{ ({} | Out-String) }})\n",
                                        init_cmd.trim()
                                    ));
                                }
                                Shell::Bash | Shell::Zsh => {
                                    output.push_str(&format!(
                                        "eval \"$({})\"\n",
                                        init_cmd.trim()
                                    ));
                                }
                                Shell::Fish => {
                                    output.push_str(&format!(
                                        "{} | source\n",
                                        init_cmd.trim()
                                    ));
                                }
                            }
                        }
                    }
                }
            }
            _ => {
                // "function" (default) — original wrapping logic
                match shell {
                    Shell::PowerShell => {
                        // A statement that starts with a quote parses in
                        // *expression* mode, where the splatting operator
                        // `@args` is illegal — and since `cortx init` output is
                        // consumed by a single Invoke-Expression, one such alias
                        // is a parse error that takes down the whole block, not
                        // just itself. The call operator `&` forces command mode.
                        //
                        // Quoting is required in the stored command as soon as
                        // the path holds a space (the .cmd and .sh shims have no
                        // call operator to fall back on), so the generator is
                        // where the PowerShell-specific syntax has to be added.
                        let cmd = alias.command.trim();
                        let call_op = if cmd.starts_with('"') || cmd.starts_with('\'') {
                            "& "
                        } else {
                            ""
                        };
                        output.push_str(&format!(
                            "function {} {{ {}{} @args }}\n",
                            alias.name, call_op, cmd
                        ));
                    }
                    Shell::Bash | Shell::Zsh => {
                        let escaped_cmd = alias.command.replace('\'', "'\\''");
                        output.push_str(&format!(
                            "{}() {{ {} \"$@\"; }}\n",
                            alias.name, escaped_cmd
                        ));
                    }
                    Shell::Fish => {
                        output.push_str(&format!(
                            "function {}\n    {} $argv\nend\n",
                            alias.name, alias.command
                        ));
                    }
                }
            }
        }
    }

    output
}

#[cfg(test)]
mod tests {
    use super::*;

    fn func_alias(name: &str, command: &str) -> ShellAlias {
        ShellAlias::new(name.to_string(), command.to_string())
    }

    #[test]
    fn powershell_quoted_command_gets_the_call_operator() {
        let a = func_alias("payledger", r#""C:\Users\Alexis Munch\payledger.exe""#);
        let out = generate_init_script(&Shell::PowerShell, std::slice::from_ref(&a));
        assert!(
            out.contains(r#"function payledger { & "C:\Users\Alexis Munch\payledger.exe" @args }"#),
            "got: {out}"
        );
    }

    #[test]
    fn powershell_bare_command_is_left_alone() {
        // Starts with a command word: already command mode, `&` would be noise.
        let a = func_alias("onepack", r#"bun run "C:\a b\x.ts""#);
        let out = generate_init_script(&Shell::PowerShell, std::slice::from_ref(&a));
        assert!(
            out.contains(r#"function onepack { bun run "C:\a b\x.ts" @args }"#),
            "got: {out}"
        );
        assert!(!out.contains("{ &"), "got: {out}");
    }

    #[test]
    fn powershell_existing_call_operator_is_not_doubled() {
        let a = func_alias("zorg", r#"& "C:\a b\zorg.exe""#);
        let out = generate_init_script(&Shell::PowerShell, std::slice::from_ref(&a));
        assert!(out.contains(r#"{ & "C:\a b\zorg.exe" @args }"#), "got: {out}");
        assert!(!out.contains("& &"), "got: {out}");
    }

    #[test]
    fn posix_shells_need_no_call_operator() {
        // In sh and fish a quoted string is a perfectly good command word.
        let a = func_alias("payledger", r#""/opt/a b/payledger""#);
        let bash = generate_init_script(&Shell::Bash, std::slice::from_ref(&a));
        assert!(bash.contains(r#"payledger() { "/opt/a b/payledger" "$@"; }"#), "got: {bash}");
        let fish = generate_init_script(&Shell::Fish, std::slice::from_ref(&a));
        assert!(fish.contains(r#""/opt/a b/payledger" $argv"#), "got: {fish}");
    }
}
