//! Resume-command building (`claude --resume`, `codex resume`) and Warp
//! launch configurations (the only way to run a command in a new Warp tab on
//! Windows).

use super::AgentProvider;
use regex::Regex;
use std::path::PathBuf;
use std::sync::OnceLock;

/// Session ids are validated before being interpolated into any command line.
pub fn is_valid_session_id(id: &str) -> bool {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| Regex::new(r"^[0-9a-fA-F-]{8,}$").expect("session id regex"))
        .is_match(id)
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ResumeCommand {
    pub program: String,
    pub args: Vec<String>,
    pub cwd: String,
}

impl ResumeCommand {
    /// Shell-ready line (`claude --resume <id> --fork-session`). Arguments
    /// are validated ids / fixed flags, so no quoting is needed.
    pub fn command_line(&self) -> String {
        let mut s = self.program.clone();
        for a in &self.args {
            s.push(' ');
            s.push_str(a);
        }
        s
    }
}

pub fn build_resume_command(
    provider: AgentProvider,
    session_id: &str,
    fork: bool,
    cwd: &str,
) -> Result<ResumeCommand, String> {
    if !is_valid_session_id(session_id) {
        return Err(format!("Invalid session id: {}", session_id));
    }
    let (program, args) = match (provider, fork) {
        (AgentProvider::ClaudeCode, false) => ("claude", vec!["--resume", session_id]),
        (AgentProvider::ClaudeCode, true) => {
            ("claude", vec!["--resume", session_id, "--fork-session"])
        }
        (AgentProvider::Codex, false) => ("codex", vec!["resume", session_id]),
        (AgentProvider::Codex, true) => ("codex", vec!["fork", session_id]),
    };
    Ok(ResumeCommand {
        program: program.to_string(),
        args: args.into_iter().map(String::from).collect(),
        cwd: cwd.to_string(),
    })
}

/// Short, filesystem-safe name for a session-specific launch config.
pub fn warp_config_name(session_id: &str) -> String {
    let short: String = session_id
        .chars()
        .filter(|c| c.is_ascii_alphanumeric())
        .take(8)
        .collect();
    format!("cortx-agent-{}", short.to_lowercase())
}

fn yaml_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => {}
            '\t' => out.push_str("\\t"),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

/// One tab of a Warp launch configuration.
pub struct WarpTab<'a> {
    pub title: &'a str,
    pub cwd: &'a str,
    pub exec: &'a str,
}

/// Warp launch configuration YAML (format documented in Warp's own template:
/// `windows[].tabs[].layout.{cwd,commands[].exec}`).
pub fn warp_launch_config_yaml(name: &str, tabs: &[WarpTab]) -> String {
    let mut y = String::new();
    y.push_str("# Generated by CortX (Agents section). Safe to delete.\n---\n");
    y.push_str(&format!("name: {}\n", yaml_quote(name)));
    y.push_str("active_window_index: 0\nwindows:\n  - active_tab_index: 0\n    tabs:\n");
    for tab in tabs {
        y.push_str(&format!("      - title: {}\n", yaml_quote(tab.title)));
        y.push_str("        layout:\n");
        y.push_str(&format!("          cwd: {}\n", yaml_quote(tab.cwd)));
        y.push_str("          commands:\n");
        y.push_str(&format!("            - exec: {}\n", yaml_quote(tab.exec)));
    }
    y
}

/// `%APPDATA%\warp\Warp\data\launch_configurations` (Windows) or the
/// platform equivalent.
pub fn warp_launch_config_dir() -> Option<PathBuf> {
    #[cfg(target_os = "windows")]
    {
        let appdata = std::env::var_os("APPDATA")?;
        Some(
            PathBuf::from(appdata)
                .join("warp")
                .join("Warp")
                .join("data")
                .join("launch_configurations"),
        )
    }
    #[cfg(target_os = "macos")]
    {
        let home = directories::BaseDirs::new()?.home_dir().to_path_buf();
        Some(home.join(".warp").join("launch_configurations"))
    }
    #[cfg(all(not(target_os = "windows"), not(target_os = "macos")))]
    {
        let base = directories::BaseDirs::new()?;
        Some(
            base.data_local_dir()
                .join("warp-terminal")
                .join("launch_configurations"),
        )
    }
}

/// Write `<name>.yaml` and return its path.
pub fn write_warp_launch_config(name: &str, tabs: &[WarpTab]) -> Result<PathBuf, String> {
    let dir = warp_launch_config_dir().ok_or("Cannot locate the Warp launch configuration folder")?;
    std::fs::create_dir_all(&dir).map_err(|e| format!("Cannot create {}: {}", dir.display(), e))?;
    let path = dir.join(format!("{}.yaml", name));
    std::fs::write(&path, warp_launch_config_yaml(name, tabs))
        .map_err(|e| format!("Cannot write {}: {}", path.display(), e))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn validates_ids() {
        assert!(is_valid_session_id("93ab4258-5362-418c-bb89-ea26d2df0ac4"));
        assert!(is_valid_session_id("01a05322-b2c8-7861-960f-dde9cdbc9a60"));
        assert!(!is_valid_session_id("abc"));
        assert!(!is_valid_session_id("93ab4258; rm -rf /"));
        assert!(!is_valid_session_id(""));
    }

    #[test]
    fn builds_commands() {
        let c = build_resume_command(AgentProvider::ClaudeCode, "93ab4258-5362", false, "C:\\x").unwrap();
        assert_eq!(c.command_line(), "claude --resume 93ab4258-5362");
        let c = build_resume_command(AgentProvider::ClaudeCode, "93ab4258-5362", true, "C:\\x").unwrap();
        assert_eq!(c.command_line(), "claude --resume 93ab4258-5362 --fork-session");
        let c = build_resume_command(AgentProvider::Codex, "01a05322-b2c8", false, "/p").unwrap();
        assert_eq!(c.command_line(), "codex resume 01a05322-b2c8");
        let c = build_resume_command(AgentProvider::Codex, "01a05322-b2c8", true, "/p").unwrap();
        assert_eq!(c.command_line(), "codex fork 01a05322-b2c8");
        assert!(build_resume_command(AgentProvider::Codex, "x", true, "/p").is_err());
    }

    #[test]
    fn warp_yaml_escapes_backslashes() {
        let y = warp_launch_config_yaml(
            "cortx-agent-93ab4258",
            &[WarpTab {
                title: "Dashboard \"agents\"",
                cwd: r"C:\Users\Me\Proj",
                exec: "claude --resume 93ab4258",
            }],
        );
        assert!(y.contains("name: \"cortx-agent-93ab4258\""));
        assert!(y.contains(r#"cwd: "C:\\Users\\Me\\Proj""#));
        assert!(y.contains(r#"title: "Dashboard \"agents\"""#));
        assert!(y.contains("- exec: \"claude --resume 93ab4258\""));
        assert_eq!(warp_config_name("93ab4258-5362-418c"), "cortx-agent-93ab4258");
    }
}
